version: 2
updates:
  # Create PRs for dependency updates
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps:"
    # Skip gardaner packages. These shall be updated manually.
    ignore:
      - dependency-name: github.com/gardener/*
        versions:
          - "*"
    labels:
    - kind/enhancement

  # Create PRs for tool updates
  - package-ecosystem: gomod
    directory: /tools
    schedule:
      interval: weekly
    commit-message:
      prefix: "tools: "
    labels:
    - kind/enhancement

  # Create PRs for golang version updates
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps:"
    labels:
    - kind/enhancement
